server:
  port: 8050
spring:
  application:
    name: geek-zipkin
eureka:
  client:
    service-url:
      # \u6307\u5B9Aeureka server\u901A\u4FE1\u5730\u5740\uFF0C\u6CE8\u610F/eureka/\u5C0F\u5C3E\u5DF4\u4E0D\u80FD\u5C11
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
  instance:
    # \u662F\u5426\u6CE8\u518CIP\u5230eureka server\uFF0C\u5982\u4E0D\u6307\u5B9A\u6216\u8BBE\u4E3Afalse\uFF0C\u90A3\u5C31\u4F1A\u6CE8\u518C\u4E3B\u673A\u540D\u5230eureka server
    prefer-ip-address: true

#zipkin\u542F\u52A8\u62A5\u9519\u65E0\u6CD5\u8BBF\u95EE\u7684\u89E3\u51B3\u65B9\u6CD5
management:
  metrics:
    web:
      server:
        auto-time-requests: false
