server:
  port: 8030

spring:
  application:
    name: geek-hystrix

eureka:
  client:
    service-url:
      # \u6307\u5B9Aeureka server\u901A\u4FE1\u5730\u5740\uFF0C\u6CE8\u610F/eureka/\u5C0F\u5C3E\u5DF4\u4E0D\u80FD\u5C11
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
  instance:
    # \u662F\u5426\u6CE8\u518CIP\u5230eureka server\uFF0C\u5982\u4E0D\u6307\u5B9A\u6216\u8BBE\u4E3Afalse\uFF0C\u90A3\u5C31\u4F1A\u6CE8\u518C\u4E3B\u673A\u540D\u5230eureka server
    prefer-ip-address: true

turbine:
  # \u8981\u76D1\u63A7\u7684\u5FAE\u670D\u52A1\u5217\u8868\uFF0C\u591A\u4E2A\u7528,\u5206\u9694
  appConfig: geek-auth,geek-upms
  clusterNameExpression: "'default'"
