server:
  port: 8030

spring:
  application:
    name: geek-hystrix

eureka:
  client:
    service-url:
      # 指定eureka server通信地址，注意/eureka/小尾巴不能少
      defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/
  instance:
    # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
    prefer-ip-address: true

turbine:
  # \u8981\u76D1\u63A7\u7684\u5FAE\u670D\u52A1\u5217\u8868\uFF0C\u591A\u4E2A\u7528,\u5206\u9694
  appConfig: geek-auth,geek-upms
  clusterNameExpression: "'default'"
